services: 
    client:
        build:
            context: ./
            dockerfile: client/Dockerfile
        ports:
            - 8080:8080
        restart: always
    nginx:
        depends_on:
            - client
            - server
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
        restart: always
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./env:/home/env:ro
        ports:
            - 3000:3000
        restart: always